# this file is generated by rake gemspec:generate for github
Gem::Specification.new do |s|
  s.name = %q{unit_controller}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Dan Manges"]
  s.date = %q{2008-10-11}
  s.description = %q{UnitController assists with unit testing controllers by stubbing view rendering.}
  s.email = %q{daniel.manges@gmail.com}
  s.files = ["lib/unit_controller/capture_render.rb", "lib/unit_controller/test_case_extension.rb", "lib/unit_controller.rb", "test/sample_controller.rb", "test/test_case_test.rb", "test/test_helper.rb", "test/unit_controller_test.rb", "README.markdown", "LICENSE", "Rakefile"]
  s.homepage = %q{http://unit-controller.rubyforge.org}
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{unit-controller}
  s.rubygems_version = %q{1.2.0}
  s.summary = %q{UnitController assists with unit testing controllers by stubbing view rendering.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 2

    if current_version >= 3 then
    else
    end
  else
  end
end
